INSERT INTO taurischema.DEPARTAMENTO VALUES (5, 'Antioquia');
INSERT INTO taurischema.DEPARTAMENTO VALUES (15, 'Boyacá');
INSERT INTO taurischema.DEPARTAMENTO VALUES (23, 'Córdoba');
INSERT INTO taurischema.DEPARTAMENTO VALUES (27, 'Chocó');
INSERT INTO taurischema.DEPARTAMENTO VALUES (52, 'Nariño');
INSERT INTO taurischema.DEPARTAMENTO VALUES (68, 'Santander');
INSERT INTO taurischema.DEPARTAMENTO VALUES (50, 'Meta');
INSERT INTO taurischema.DEPARTAMENTO VALUES (8, 'Atlántico');
INSERT INTO taurischema.DEPARTAMENTO VALUES (13, 'Bolívar');
INSERT INTO taurischema.DEPARTAMENTO VALUES (17, 'Caldas');
INSERT INTO taurischema.DEPARTAMENTO VALUES (18, 'Caquetá');
INSERT INTO taurischema.DEPARTAMENTO VALUES (19, 'Cauca');
INSERT INTO taurischema.DEPARTAMENTO VALUES (20, 'Cesar');
INSERT INTO taurischema.DEPARTAMENTO VALUES (25, 'Cundinamarca');
INSERT INTO taurischema.DEPARTAMENTO VALUES (41, 'Huila');
INSERT INTO taurischema.DEPARTAMENTO VALUES (44, 'La Guajira');
INSERT INTO taurischema.DEPARTAMENTO VALUES (47, 'Magdalena');
INSERT INTO taurischema.DEPARTAMENTO VALUES (63, 'Quindío');
INSERT INTO taurischema.DEPARTAMENTO VALUES (66, 'Risaralda');
INSERT INTO taurischema.DEPARTAMENTO VALUES (70, 'Sucre');
INSERT INTO taurischema.DEPARTAMENTO VALUES (73, 'Tolima');
INSERT INTO taurischema.DEPARTAMENTO VALUES (81, 'Arauca');
INSERT INTO taurischema.DEPARTAMENTO VALUES (85, 'Casanare');
INSERT INTO taurischema.DEPARTAMENTO VALUES (86, 'Putumayo');
INSERT INTO taurischema.DEPARTAMENTO VALUES (91, 'Amazonas');
INSERT INTO taurischema.DEPARTAMENTO VALUES (94, 'Guainía');
INSERT INTO taurischema.DEPARTAMENTO VALUES (97, 'Vaupés');
INSERT INTO taurischema.DEPARTAMENTO VALUES (99, 'Vichada');
INSERT INTO taurischema.DEPARTAMENTO VALUES (95, 'Guaviare');
INSERT INTO taurischema.DEPARTAMENTO VALUES (88, 'Archipiélago de San Andrés, Providencia y Santa Catalina');
INSERT INTO taurischema.DEPARTAMENTO VALUES (11, 'Bogotá D.C.');
INSERT INTO taurischema.DEPARTAMENTO VALUES (54, 'Norte de Santander');
INSERT INTO taurischema.DEPARTAMENTO VALUES (76, 'Valle del Cauca');
