INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Medellín', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 2, 'Abejorral', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 4, 'Abriaquí', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 21, 'Alejandría', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 3, 'Amagá', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 31, 'Amalfi', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 34, 'Andes', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 36, 'Angelópolis', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 38, 'Angostura', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 4, 'Anorí', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 832, 'Tununguá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 44, 'Anza', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 45, 'Apartadó', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 51, 'Arboletes', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 55, 'Argelia', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 59, 'Armenia', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 79, 'Barbosa', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 88, 'Bello', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 91, 'Betania', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 93, 'Betulia', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 101, 'Ciudad Bolívar', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 107, 'Briceño', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 113, 'Buriticá', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 12, 'Cáceres', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 125, 'Caicedo', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 129, 'Caldas', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 134, 'Campamento', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 138, 'Cañasgordas', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 142, 'Caracolí', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 145, 'Caramanta', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 147, 'Carepa', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 476, 'Motavita', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 15, 'Carolina', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 154, 'Caucasia', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 172, 'Chigorodó', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 19, 'Cisneros', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 197, 'Cocorná', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 206, 'Concepción', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 209, 'Concordia', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 212, 'Copacabana', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 234, 'Dabeiba', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 237, 'Don Matías', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 24, 'Ebéjico', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 25, 'El Bagre', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 264, 'Entrerrios', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 266, 'Envigado', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 282, 'Fredonia', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 675, 'San Bernardo del Viento', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 306, 'Giraldo', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 308, 'Girardota', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 31, 'Gómez Plata', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 361, 'Istmina', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 315, 'Guadalupe', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 318, 'Guarne', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 321, 'Guatapé', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 347, 'Heliconia', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 353, 'Hispania', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 36, 'Itagui', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 361, 'Ituango', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 86, 'Belmira', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 368, 'Jericó', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 376, 'La Ceja', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 38, 'La Estrella', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 39, 'La Pintada', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 4, 'La Unión', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 411, 'Liborina', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 425, 'Maceo', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 44, 'Marinilla', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 467, 'Montebello', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 475, 'Murindó', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 48, 'Mutatá', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 483, 'Nariño', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 49, 'Necoclí', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 495, 'Nechí', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 501, 'Olaya', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 541, 'Peñol', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 543, 'Peque', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 576, 'Pueblorrico', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 579, 'Puerto Berrío', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 585, 'Puerto Nare', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 591, 'Puerto Triunfo', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 604, 'Remedios', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 607, 'Retiro', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 615, 'Rionegro', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 628, 'Sabanalarga', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 631, 'Sabaneta', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 642, 'Salgar', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 189, 'Ciénega', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 699, 'Santacruz', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 652, 'San Francisco', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 656, 'San Jerónimo', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 575, 'Puerto Wilches', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 573, 'Puerto Parra', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 66, 'San Luis', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 664, 'San Pedro', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 667, 'San Rafael', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 67, 'San Roque', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 674, 'San Vicente', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 679, 'Santa Bárbara', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 69, 'Santo Domingo', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 697, 'El Santuario', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 736, 'Segovia', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 761, 'Sopetrán', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 37, 'Uribe', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 789, 'Támesis', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 79, 'Tarazá', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 792, 'Tarso', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 809, 'Titiribí', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 819, 'Toledo', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 837, 'Turbo', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 842, 'Uramita', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 847, 'Urrao', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 854, 'Valdivia', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 856, 'Valparaíso', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 858, 'Vegachí', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 861, 'Venecia', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 885, 'Yalí', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 887, 'Yarumal', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 89, 'Yolombó', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 893, 'Yondó', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 895, 'Zaragoza', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Barranquilla', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 78, 'Baranoa', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 141, 'Candelaria', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 296, 'Galapa', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 421, 'Luruaco', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 433, 'Malambo', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 436, 'Manatí', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 549, 'Piojó', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 558, 'Polonuevo', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 634, 'Sabanagrande', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 638, 'Sabanalarga', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 675, 'Santa Lucía', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 685, 'Santo Tomás', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 758, 'Soledad', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 77, 'Suan', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 832, 'Tubará', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 849, 'Usiacurí', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 6, 'Achí', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 42, 'Arenal', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 52, 'Arjona', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 62, 'Arroyohondo', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 14, 'Calamar', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 16, 'Cantagallo', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 188, 'Cicuco', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 212, 'Córdoba', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 222, 'Clemencia', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 248, 'El Guamo', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 43, 'Magangué', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 433, 'Mahates', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 44, 'Margarita', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 458, 'Montecristo', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 468, 'Mompós', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 473, 'Morales', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 49, 'Norosí', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 549, 'Pinillos', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 58, 'Regidor', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 6, 'Río Viejo', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 647, 'San Estanislao', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 65, 'San Fernando', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 657, 'San Juan Nepomuceno', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 673, 'Santa Catalina', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 683, 'Santa Rosa', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 744, 'Simití', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 76, 'Soplaviento', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 78, 'Talaigua Nuevo', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 81, 'Tiquisio', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 836, 'Turbaco', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 838, 'Turbaná', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 873, 'Villanueva', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Tunja', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 22, 'Almeida', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 47, 'Aquitania', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 51, 'Arcabuco', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 9, 'Berbeo', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 92, 'Betéitiva', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 97, 'Boavita', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 104, 'Boyacá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 106, 'Briceño', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 109, 'Buena Vista', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 114, 'Busbanzá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 131, 'Caldas', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 135, 'Campohermoso', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 162, 'Cerinza', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 172, 'Chinavita', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 176, 'Chiquinquirá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 18, 'Chiscas', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 183, 'Chita', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 185, 'Chitaraque', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 187, 'Chivatá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 204, 'Cómbita', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 212, 'Coper', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 215, 'Corrales', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 218, 'Covarachía', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 223, 'Cubará', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 224, 'Cucaita', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 226, 'Cuítiva', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 232, 'Chíquiza', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 236, 'Chivor', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 238, 'Duitama', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 244, 'El Cocuy', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 248, 'El Espino', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 272, 'Firavitoba', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 276, 'Floresta', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 293, 'Gachantivá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 296, 'Gameza', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 299, 'Garagoa', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 317, 'Guacamayas', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 322, 'Guateque', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 325, 'Guayatá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 332, 'Güicán', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 362, 'Iza', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 367, 'Jenesano', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 368, 'Jericó', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 377, 'Labranzagrande', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 38, 'La Capilla', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 401, 'La Victoria', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 425, 'Macanal', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 442, 'Maripí', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 455, 'Miraflores', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 464, 'Mongua', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 466, 'Monguí', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 469, 'Moniquirá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 48, 'Muzo', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 491, 'Nobsa', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 494, 'Nuevo Colón', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 5, 'Oicatá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 507, 'Otanche', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 511, 'Pachavita', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 514, 'Páez', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 516, 'Paipa', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 518, 'Pajarito', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 522, 'Panqueba', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 531, 'Pauna', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 533, 'Paya', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 542, 'Pesca', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 55, 'Pisba', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 572, 'Puerto Boyacá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 58, 'Quípama', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 599, 'Ramiriquí', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 6, 'Ráquira', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 621, 'Rondón', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 632, 'Saboyá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 638, 'Sáchica', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 646, 'Samacá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 66, 'San Eduardo', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 673, 'San Mateo', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 686, 'Santana', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 69, 'Santa María', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 696, 'Santa Sofía', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 72, 'Sativanorte', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 723, 'Sativasur', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 74, 'Siachoque', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 753, 'Soatá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 755, 'Socotá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 757, 'Socha', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 759, 'Sogamoso', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 761, 'Somondoco', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 762, 'Sora', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 763, 'Sotaquirá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 764, 'Soracá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 774, 'Susacón', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 776, 'Sutamarchán', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 778, 'Sutatenza', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 79, 'Tasco', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 798, 'Tenza', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 804, 'Tibaná', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 808, 'Tinjacá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 81, 'Tipacoque', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 814, 'Toca', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 82, 'Tópaga', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 822, 'Tota', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 835, 'Turmequé', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 839, 'Tutazá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 842, 'Umbita', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 861, 'Ventaquemada', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 879, 'Viracachá', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 897, 'Zetaquira', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Manizales', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 13, 'Aguadas', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 42, 'Anserma', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 5, 'Aranzazu', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 88, 'Belalcázar', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 174, 'Chinchiná', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 272, 'Filadelfia', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 38, 'La Dorada', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 388, 'La Merced', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 433, 'Manzanares', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 442, 'Marmato', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 446, 'Marulanda', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 486, 'Neira', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 495, 'Norcasia', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 513, 'Pácora', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 524, 'Palestina', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 541, 'Pensilvania', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 614, 'Riosucio', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 616, 'Risaralda', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 653, 'Salamina', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 662, 'Samaná', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 665, 'San José', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 777, 'Supía', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 867, 'Victoria', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 873, 'Villamaría', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 877, 'Viterbo', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Florencia', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 29, 'Albania', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 205, 'Curillo', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 247, 'El Doncello', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 256, 'El Paujil', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 479, 'Morelia', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 592, 'Puerto Rico', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 756, 'Solano', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 785, 'Solita', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 86, 'Valparaíso', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Popayán', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 22, 'Almaguer', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 5, 'Argelia', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 75, 'Balboa', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Bolívar', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 11, 'Buenos Aires', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 13, 'Cajibío', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 137, 'Caldono', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 142, 'Caloto', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 212, 'Corinto', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 256, 'El Tambo', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 29, 'Florencia', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 3, 'Guachené', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 318, 'Guapi', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 355, 'Inzá', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 364, 'Jambaló', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 392, 'La Sierra', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 397, 'La Vega', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 418, 'López', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 45, 'Mercaderes', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 455, 'Miranda', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 473, 'Morales', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 513, 'Padilla', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 532, 'Patía', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 533, 'Piamonte', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 548, 'Piendamó', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 573, 'Puerto Tejada', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 585, 'Puracé', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 622, 'Rosas', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 701, 'Santa Rosa', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 743, 'Silvia', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 76, 'Sotara', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 78, 'Suárez', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 785, 'Sucre', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 807, 'Timbío', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 809, 'Timbiquí', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 821, 'Toribio', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 824, 'Totoró', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 845, 'Villa Rica', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Valledupar', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 11, 'Aguachica', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 13, 'Agustín Codazzi', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 32, 'Astrea', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 45, 'Becerril', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 6, 'Bosconia', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 175, 'Chimichagua', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 178, 'Chiriguaná', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 228, 'Curumaní', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 238, 'El Copey', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 25, 'El Paso', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 295, 'Gamarra', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 31, 'González', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 383, 'La Gloria', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 443, 'Manaure', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 517, 'Pailitas', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 55, 'Pelaya', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 57, 'Pueblo Bello', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 621, 'La Paz', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 71, 'San Alberto', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 75, 'San Diego', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 77, 'San Martín', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 787, 'Tamalameque', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Montería', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 68, 'Ayapel', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 79, 'Buenavista', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 9, 'Canalete', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 162, 'Cereté', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 168, 'Chimá', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 182, 'Chinú', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 3, 'Cotorra', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 417, 'Lorica', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 419, 'Los Córdobas', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 464, 'Momil', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 5, 'Moñitos', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 555, 'Planeta Rica', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 57, 'Pueblo Nuevo', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 574, 'Puerto Escondido', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 586, 'Purísima', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 66, 'Sahagún', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 67, 'San Andrés Sotavento', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 672, 'San Antero', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 686, 'San Pelayo', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 807, 'Tierralta', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 815, 'Tuchín', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 855, 'Valencia', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 35, 'Anapoima', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 53, 'Arbeláez', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 86, 'Beltrán', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 95, 'Bituima', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 99, 'Bojacá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 12, 'Cabrera', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 123, 'Cachipay', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 126, 'Cajicá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 148, 'Caparrapí', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 151, 'Caqueza', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 168, 'Chaguaní', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 178, 'Chipaque', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 181, 'Choachí', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 183, 'Chocontá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 2, 'Cogua', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 214, 'Cota', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 224, 'Cucunubá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 245, 'El Colegio', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 26, 'El Rosal', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 279, 'Fomeque', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 281, 'Fosca', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 286, 'Funza', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 288, 'Fúquene', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 293, 'Gachala', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 295, 'Gachancipá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 297, 'Gachetá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 307, 'Girardot', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 312, 'Granada', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 317, 'Guachetá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 32, 'Guaduas', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 322, 'Guasca', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 324, 'Guataquí', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 326, 'Guatavita', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 335, 'Guayabetal', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 339, 'Gutiérrez', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 368, 'Jerusalén', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 372, 'Junín', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 377, 'La Calera', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 386, 'La Mesa', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 394, 'La Palma', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 398, 'La Peña', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 402, 'La Vega', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 407, 'Lenguazaque', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 426, 'Macheta', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 43, 'Madrid', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 436, 'Manta', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 438, 'Medina', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 473, 'Mosquera', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 483, 'Nariño', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 486, 'Nemocón', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 488, 'Nilo', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 489, 'Nimaima', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 491, 'Nocaima', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 506, 'Venecia', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 513, 'Pacho', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 518, 'Paime', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 524, 'Pandi', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 53, 'Paratebueno', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 535, 'Pasca', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 572, 'Puerto Salgar', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 58, 'Pulí', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 592, 'Quebradanegra', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 594, 'Quetame', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 596, 'Quipile', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 599, 'Apulo', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 612, 'Ricaurte', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 649, 'San Bernardo', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 653, 'San Cayetano', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 658, 'San Francisco', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 736, 'Sesquilé', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 74, 'Sibaté', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 743, 'Silvania', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 745, 'Simijaca', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 754, 'Soacha', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 769, 'Subachoque', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 772, 'Suesca', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 777, 'Supatá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 779, 'Susa', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 781, 'Sutatausa', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 785, 'Tabio', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 793, 'Tausa', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 797, 'Tena', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 799, 'Tenjo', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 805, 'Tibacuy', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 807, 'Tibirita', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 815, 'Tocaima', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 817, 'Tocancipá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 823, 'Topaipí', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 839, 'Ubalá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 841, 'Ubaque', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 845, 'Une', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 851, 'Útica', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 867, 'Vianí', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 871, 'Villagómez', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 873, 'Villapinzón', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 875, 'Villeta', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 878, 'Viotá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 898, 'Zipacón', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Quibdó', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 6, 'Acandí', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 25, 'Alto Baudo', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 5, 'Atrato', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 73, 'Bagadó', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 75, 'Bahía Solano', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 77, 'Bajo Baudó', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 99, 'Bojaya', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 16, 'Cértegui', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 205, 'Condoto', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 372, 'Juradó', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 413, 'Lloró', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 425, 'Medio Atrato', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 43, 'Medio Baudó', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 45, 'Medio San Juan', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 491, 'Nóvita', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 495, 'Nuquí', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 58, 'Río Iro', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 6, 'Río Quito', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 615, 'Riosucio', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 745, 'Sipí', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 8, 'Unguía', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Neiva', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 6, 'Acevedo', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 13, 'Agrado', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 16, 'Aipe', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 2, 'Algeciras', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 26, 'Altamira', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 78, 'Baraya', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 132, 'Campoalegre', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 206, 'Colombia', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 244, 'Elías', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 298, 'Garzón', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 306, 'Gigante', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 319, 'Guadalupe', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 349, 'Hobo', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 357, 'Iquira', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 359, 'Isnos', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 378, 'La Argentina', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 396, 'La Plata', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 483, 'Nátaga', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 503, 'Oporapa', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 518, 'Paicol', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 524, 'Palermo', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 53, 'Palestina', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 548, 'Pital', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 551, 'Pitalito', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 615, 'Rivera', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 66, 'Saladoblanco', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 676, 'Santa María', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 77, 'Suaza', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 791, 'Tarqui', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 797, 'Tesalia', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 799, 'Tello', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 801, 'Teruel', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 807, 'Timaná', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 872, 'Villavieja', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 885, 'Yaguará', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Riohacha', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 35, 'Albania', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 78, 'Barrancas', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 9, 'Dibula', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 98, 'Distracción', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 11, 'El Molino', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 279, 'Fonseca', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 378, 'Hatonuevo', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 43, 'Maicao', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 56, 'Manaure', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 847, 'Uribia', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 855, 'Urumita', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 874, 'Villanueva', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Santa Marta', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 3, 'Algarrobo', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 53, 'Aracataca', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 58, 'Ariguaní', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 161, 'Cerro San Antonio', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 17, 'Chivolo', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 205, 'Concordia', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 245, 'El Banco', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 258, 'El Piñon', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 268, 'El Retén', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 288, 'Fundación', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 318, 'Guamal', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 46, 'Nueva Granada', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 541, 'Pedraza', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 551, 'Pivijay', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 555, 'Plato', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 605, 'Remolino', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 675, 'Salamina', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 703, 'San Zenón', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 707, 'Santa Ana', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 745, 'Sitionuevo', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 798, 'Tenerife', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 96, 'Zapayán', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 98, 'Zona Bananera', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Villavicencio', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 6, 'Acacias', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 124, 'Cabuyaro', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 223, 'Cubarral', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 226, 'Cumaral', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 245, 'El Calvario', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 251, 'El Castillo', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 27, 'El Dorado', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 313, 'Granada', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 318, 'Guamal', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 325, 'Mapiripán', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 33, 'Mesetas', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 35, 'La Macarena', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 4, 'Lejanías', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 45, 'Puerto Concordia', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 568, 'Puerto Gaitán', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 573, 'Puerto López', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 577, 'Puerto Lleras', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 59, 'Puerto Rico', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 606, 'Restrepo', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 686, 'San Juanito', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 689, 'San Martín', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 711, 'Vista Hermosa', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Pasto', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 19, 'Albán', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 22, 'Aldana', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 36, 'Ancuyá', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 79, 'Barbacoas', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 203, 'Colón', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 207, 'Consaca', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 21, 'Contadero', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 215, 'Córdoba', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 224, 'Cuaspud', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 227, 'Cumbal', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 233, 'Cumbitara', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 25, 'El Charco', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 254, 'El Peñol', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 256, 'El Rosario', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 26, 'El Tambo', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 287, 'Funes', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 317, 'Guachucal', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 32, 'Guaitarilla', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 323, 'Gualmatán', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 352, 'Iles', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 354, 'Imués', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 356, 'Ipiales', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 378, 'La Cruz', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 381, 'La Florida', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 385, 'La Llanada', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 39, 'La Tola', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 399, 'La Unión', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 405, 'Leiva', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 411, 'Linares', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 418, 'Los Andes', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 427, 'Magüí', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 435, 'Mallama', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 473, 'Mosquera', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 48, 'Nariño', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 49, 'Olaya Herrera', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 506, 'Ospina', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 52, 'Francisco Pizarro', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 54, 'Policarpa', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 56, 'Potosí', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 565, 'Providencia', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 573, 'Puerres', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 585, 'Pupiales', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 612, 'Ricaurte', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 621, 'Roberto Payán', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 678, 'Samaniego', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 683, 'Sandoná', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 685, 'San Bernardo', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 687, 'San Lorenzo', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 693, 'San Pablo', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 696, 'Santa Bárbara', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 72, 'Sapuyes', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 786, 'Taminango', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 788, 'Tangua', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 838, 'Túquerres', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 885, 'Yacuanquer', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Armenia', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 111, 'Buenavista', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 19, 'Circasia', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 212, 'Córdoba', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 272, 'Filandia', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 401, 'La Tebaida', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 47, 'Montenegro', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 548, 'Pijao', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 594, 'Quimbaya', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 69, 'Salento', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Pereira', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 45, 'Apía', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 75, 'Balboa', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 17, 'Dosquebradas', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 318, 'Guática', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 383, 'La Celia', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 4, 'La Virginia', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 44, 'Marsella', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 456, 'Mistrató', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 572, 'Pueblo Rico', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 594, 'Quinchía', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 687, 'Santuario', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Bucaramanga', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 13, 'Aguada', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 2, 'Albania', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 51, 'Aratoca', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 77, 'Barbosa', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 79, 'Barichara', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 81, 'Barrancabermeja', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 92, 'Betulia', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 101, 'Bolívar', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 121, 'Cabrera', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 132, 'California', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 152, 'Carcasí', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 16, 'Cepitá', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 162, 'Cerrito', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 167, 'Charalá', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 169, 'Charta', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 179, 'Chipatá', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 19, 'Cimitarra', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 207, 'Concepción', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 209, 'Confines', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 211, 'Contratación', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 217, 'Coromoro', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 229, 'Curití', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 245, 'El Guacamayo', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 255, 'El Playón', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 264, 'Encino', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 266, 'Enciso', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 271, 'Florián', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 276, 'Floridablanca', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 296, 'Galán', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 298, 'Gambita', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 307, 'Girón', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 318, 'Guaca', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 32, 'Guadalupe', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 322, 'Guapotá', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 324, 'Guavatá', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 327, 'Güepsa', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 368, 'Jesús María', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 37, 'Jordán', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 377, 'La Belleza', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 385, 'Landázuri', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 397, 'La Paz', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 406, 'Lebríja', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 418, 'Los Santos', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 425, 'Macaravita', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 432, 'Málaga', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 444, 'Matanza', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 464, 'Mogotes', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 468, 'Molagavita', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 498, 'Ocamonte', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 5, 'Oiba', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 502, 'Onzaga', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 522, 'Palmar', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 533, 'Páramo', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 547, 'Piedecuesta', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 549, 'Pinchote', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 572, 'Puente Nacional', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 615, 'Rionegro', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 669, 'San Andrés', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 679, 'San Gil', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 682, 'San Joaquín', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 686, 'San Miguel', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 705, 'Santa Bárbara', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 745, 'Simacota', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 755, 'Socorro', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 77, 'Suaita', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 773, 'Sucre', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 78, 'Suratá', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 82, 'Tona', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 861, 'Vélez', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 867, 'Vetas', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 872, 'Villanueva', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 895, 'Zapatoca', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Sincelejo', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 11, 'Buenavista', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 124, 'Caimito', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 204, 'Coloso', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 221, 'Coveñas', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 23, 'Chalán', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 233, 'El Roble', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 235, 'Galeras', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 265, 'Guaranda', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 4, 'La Unión', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 418, 'Los Palmitos', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 429, 'Majagual', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 473, 'Morroa', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 508, 'Ovejas', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 523, 'Palmito', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 678, 'San Benito Abad', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 708, 'San Marcos', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 713, 'San Onofre', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 717, 'San Pedro', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 771, 'Sucre', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 823, 'Tolú Viejo', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 24, 'Alpujarra', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 26, 'Alvarado', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 3, 'Ambalema', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 55, 'Armero', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 67, 'Ataco', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 124, 'Cajamarca', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 168, 'Chaparral', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 2, 'Coello', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 217, 'Coyaima', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 226, 'Cunday', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 236, 'Dolores', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 268, 'Espinal', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 27, 'Falan', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 275, 'Flandes', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 283, 'Fresno', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 319, 'Guamo', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 347, 'Herveo', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 349, 'Honda', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 352, 'Icononzo', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 443, 'Mariquita', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 449, 'Melgar', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 461, 'Murillo', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 483, 'Natagaima', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 504, 'Ortega', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 52, 'Palocabildo', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 547, 'Piedras', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 555, 'Planadas', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 563, 'Prado', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 585, 'Purificación', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 616, 'Rio Blanco', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 622, 'Roncesvalles', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 624, 'Rovira', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 671, 'Saldaña', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 686, 'Santa Isabel', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 861, 'Venadillo', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 87, 'Villahermosa', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 873, 'Villarrica', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 65, 'Arauquita', 81);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 22, 'Cravo Norte', 81);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 3, 'Fortul', 81);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 591, 'Puerto Rondón', 81);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 736, 'Saravena', 81);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 794, 'Tame', 81);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Arauca', 81);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Yopal', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Aguazul', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 15, 'Chámeza', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 125, 'Hato Corozal', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 136, 'La Salina', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 162, 'Monterrey', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 263, 'Pore', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 279, 'Recetor', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 3, 'Sabanalarga', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 315, 'Sácama', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 41, 'Tauramena', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 43, 'Trinidad', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 44, 'Villanueva', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Mocoa', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 219, 'Colón', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 32, 'Orito', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 569, 'Puerto Caicedo', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 571, 'Puerto Guzmán', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 573, 'Leguízamo', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 749, 'Sibundoy', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 755, 'San Francisco', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 757, 'San Miguel', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 76, 'Santiago', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Leticia', 91);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 263, 'El Encanto', 91);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 405, 'La Chorrera', 91);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 407, 'La Pedrera', 91);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 43, 'La Victoria', 91);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 536, 'Puerto Arica', 91);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 54, 'Puerto Nariño', 91);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 669, 'Puerto Santander', 91);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 798, 'Tarapacá', 91);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Inírida', 94);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 343, 'Barranco Minas', 94);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 663, 'Mapiripana', 94);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 883, 'San Felipe', 94);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 884, 'Puerto Colombia', 94);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 885, 'La Guadalupe', 94);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 886, 'Cacahual', 94);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 887, 'Pana Pana', 94);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Mitú', 97);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 161, 'Carurú', 97);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 666, 'Taraira', 97);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 777, 'Papunahua', 97);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 889, 'Yavaraté', 97);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 511, 'Pacoa', 97);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 888, 'Morichal', 94);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Puerto Carreño', 99);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 524, 'La Primavera', 99);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 624, 'Santa Rosalía', 99);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 773, 'Cumaribo', 99);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 61, 'San José del Fragua', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 11, 'Barranca de Upía', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 524, 'Palmas del Socorro', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 662, 'San Juan de Río Seco', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 372, 'Juan de Acosta', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 287, 'Fuente de Oro', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 325, 'San Luis de Gaceno', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 25, 'El Litoral del San Juan', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 843, 'Villa de San Diego de Ubate', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 74, 'Barranco de Loba', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 816, 'Togüí', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 688, 'Santa Rosa del Sur', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 135, 'El Cantón del San Pablo', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 407, 'Villa de Leyva', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 692, 'San Sebastián de Buenavista', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 537, 'Paz de Río', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 3, 'Hatillo de Loba', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 66, 'Sabanas de San Angel', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 15, 'Calamar', 95);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 614, 'Río de Oro', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 665, 'San Pedro de Uraba', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'San José del Guaviare', 95);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 693, 'Santa Rosa de Viterbo', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 698, 'Santander de Quilichao', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 2, 'Miraflores', 95);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 42, 'Santafé de Antioquia', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 68, 'San Carlos de Guaroa', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 52, 'Palmar de Varela', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 686, 'Santa Rosa de Osos', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 647, 'San Andrés de Cuerquía', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 854, 'Valle de San Juan', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 689, 'San Vicente de Chucurí', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 684, 'San José de Miranda', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 564, 'Providencia', 88);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 682, 'Santa Rosa de Cabal', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 328, 'Guayabal de Siquima', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 94, 'Belén de Los Andaquies', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 25, 'Paz de Ariporo', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 72, 'Santa Helena del Opón', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 681, 'San Pablo de Borbur', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 42, 'La Jagua del Pilar', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 4, 'La Jagua de Ibirico', 20);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 742, 'San Luis de Sincé', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 667, 'San Luis de Gaceno', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 244, 'El Carmen de Bolívar', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 245, 'El Carmen de Atrato', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 702, 'San Juan de Betulia', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 545, 'Pijiño del Carmen', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 873, 'Vigía del Fuerte', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 667, 'San Martín de Loba', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 3, 'Altos del Rosario', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 148, 'Carmen de Apicala', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 645, 'San Antonio del Tequendama', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 655, 'Sabana de Torres', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 25, 'El Retorno', 95);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 682, 'San José de Uré', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 694, 'San Pedro de Cartago', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 137, 'Campo de La Cruz', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 683, 'San Juan de Arama', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 658, 'San José de La Montaña', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 15, 'Cartagena del Chairá', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 66, 'San José del Palmar', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Agua de Dios', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 655, 'San Jacinto del Cauca', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 668, 'San Agustín', 41);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 258, 'El Tablón de Gómez', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'San Andrés', 88);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 664, 'San José de Pare', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 865, 'Valle de Guamez', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 67, 'San Pablo de Borbur', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 82, 'Santiago de Tolú', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Bogotá D.C.', 11);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 154, 'Carmen de Carupa', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 189, 'Ciénaga de Oro', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 659, 'San Juan de Urabá', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 65, 'San Juan del Cesar', 44);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 235, 'El Carmen de Chucurí', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 148, 'El Carmen de Viboral', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 88, 'Belén de Umbría', 66);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 86, 'Belén de Bajira', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 855, 'Valle de San José', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 678, 'San Luis', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 676, 'San Miguel de Sema', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 675, 'San Antonio', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 673, 'San Benito', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 862, 'Vergara', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 678, 'San Carlos', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 53, 'Puerto Alegría', 91);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 344, 'Hato', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 654, 'San Jacinto', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 693, 'San Sebastián', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 649, 'San Carlos', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 837, 'Tuta', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 743, 'Silos', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 125, 'Cácota', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 25, 'El Dovio', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 82, 'Toledo', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 622, 'Roldanillo', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 48, 'Mutiscua', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 54, 'Argelia', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 261, 'El Zulia', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 66, 'Salazar', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 736, 'Sevilla', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 895, 'Zarzal', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 223, 'Cucutilla', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 248, 'El Cerrito', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 147, 'Cartago', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 122, 'Caicedonia', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 553, 'Puerto Santander', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 313, 'Gramalote', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 246, 'El Cairo', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 25, 'El Tarra', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 4, 'La Unión', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 606, 'Restrepo', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 8, 'Teorama', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 233, 'Dagua', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 51, 'Arboledas', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 318, 'Guacarí', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 418, 'Lourdes', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 41, 'Ansermanuevo', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 99, 'Bochalema', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 113, 'Bugalagrande', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 206, 'Convención', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 344, 'Hacarí', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 403, 'La Victoria', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 347, 'Herrán', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 306, 'Ginebra', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 892, 'Yumbo', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 497, 'Obando', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 81, 'Tibú', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 673, 'San Cayetano', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 67, 'San Calixto', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Bolívar', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 398, 'La Playa', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Cali', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 67, 'San Pedro', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 111, 'Guadalajara de Buga', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 172, 'Chinácota', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 599, 'Ragonvalia', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 385, 'La Esperanza', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 874, 'Villa del Rosario', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 174, 'Chitagá', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 126, 'Calima', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 72, 'Sardinata', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 36, 'Andalucía', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 563, 'Pradera', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 3, 'Abrego', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 405, 'Los Patios', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 498, 'Ocaña', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 109, 'Bucarasica', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 89, 'Yotoco', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 52, 'Palmira', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 616, 'Riofrío', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 68, 'Santiago', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 2, 'Alcalá', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 863, 'Versalles', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 377, 'Labateca', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 128, 'Cachirá', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 871, 'Villa Caro', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 239, 'Durania', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 243, 'El Águila', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 823, 'Toro', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 13, 'Candelaria', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 377, 'La Cumbre', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 845, 'Ulloa', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 828, 'Trujillo', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 869, 'Vijes', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 176, 'Chimá', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 67, 'Sampués', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 225, 'Nunchía', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 518, 'Pamplona', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 19, 'Albán', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 466, 'Montelíbano', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 568, 'Puerto Asís', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 215, 'Corozal', 70);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 11, 'Buesaco', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 139, 'Maní', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 268, 'El Peñón', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 834, 'Tuluá', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 152, 'Casabianca', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 4, 'Anolaima', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 175, 'Chía', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 835, 'San Andrés de Tumaco', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 46, 'Milán', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 147, 'Capitanejo', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 43, 'Anzoátegui', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 275, 'Florida', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 606, 'Repelón', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 284, 'Frontino', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 258, 'El Peñón', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 52, 'Pamplonita', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 46, 'Miriti Paraná', 91);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 4, 'Támara', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 806, 'Tibasosa', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 517, 'Páez', 19);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Ibagué', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 573, 'Puerto Colombia', 8);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 83, 'Belén', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 758, 'Sopó', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 15, 'Carmen del Darien', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 299, 'Gama', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 718, 'Sasaima', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 24, 'Chachagüí', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Cúcuta', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 1, 'Cartagena', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 313, 'Granada', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 72, 'Santa Bárbara de Pinto', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 442, 'María la Baja', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 41, 'La Montañita', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 753, 'San Vicente del Caguán', 18);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 25, 'El Peñón', 68);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 364, 'Jardín', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 364, 'Jamundí', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 787, 'Tadó', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 23, 'Orocué', 85);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 411, 'Líbano', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 885, 'Yacopí', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 13, 'Calarcá', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 756, 'Sonsón', 5);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 245, 'El Carmen', 54);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 408, 'Lérida', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 35, 'La Apartada', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 62, 'San Cristóbal', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 29, 'Fusagasugá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 894, 'Zambrano', 13);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 403, 'La Uvita', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 899, 'Zipaquirá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 302, 'Génova', 63);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 77, 'Suárez', 73);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 15, 'Castilla la Nueva', 50);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 87, 'Belén', 15);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 81, 'Unión Panamericana', 27);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 57, 'Pueblo Viejo', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 885, 'Villagarzón', 86);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 269, 'Facatativá', 25);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 58, 'Puerto Libertador', 23);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 444, 'Marquetalia', 17);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 51, 'Arboleda', 52);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 109, 'Buenaventura', 76);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 189, 'Ciénaga', 47);
INSERT INTO MUNICIPIO VALUES(nextval('seq_municipio'), 56, 'Ponedera', 8);

