create table biblioteca (
	id serial not null,
	nombre character varying (100) not null,
	categoria character varying (100) not null,
	tipo character varying (50) not null,
	ms float null,
	ed float null,
	fda float null, 
	fdn float null, 
	pb float null,
	almidon float null,
	fraccion_a integer null,
	fraccion_b integer null,
	fraccion_c integer null,
	digestabilidad_pndr float null,
	kd_fraccion_b float null,
	pndr float null,
	grasa_cruda float null,
	cenizas float null,
	porcentaje_ca float null,
	porcentaje_p float null,
	porcentaje_na float null,
	porcentaje_cl float null,
	porcentaje_k float null,
	porcentaje_mg float null,
	porcentaje_s float null,
	coeficiente_absorcion_ca float null,
	coeficiente_absorcion_p float null,
	coeficiente_absorcion_na float null,
	coeficiente_absorcion_cl float null,
	coeficiente_absorcion_k float null,
	usuario character varying (100) not null,
	primary key (id)
);